// English teaching text; geometry comes from the reviewed local studies.
export const motions = {
  'travelling-wave': {title:'A wave travels along a line',kind:'Travelling deformation',description:'The spiral stays in place while small bends travel along its continuous line. Closely spaced turns make the surface appear to move.',controls:'Spiral: Radius 48 mm, Pitch 6 mm. Zigzag Path: Sine, Wavelength 22 mm, Amplitude 2 mm. Phase runs from 0 to 1.',change:'Try Amplitude 1–3 mm. A shorter Wavelength makes a busier surface; a longer one makes a calmer movement.',plot:'One continuous path: a useful first plotting test. Use 48 frames for a smoother travelling wave.'},
  'sliding-moire': {title:'Two fields of rings pulse',kind:'Interference',description:'Two ring fields slide through one another. The light and dark bands between them appear to move differently from the rings themselves.',controls:'Rings: Radius 39 mm, Pitch 2 / 2.1 mm. The X centres move in opposite directions, over 39–51% and 49–61%.',change:'Reduce the difference in Pitch for finer interference. Keep the angles fixed and try moving only one field.',plot:'One pen emphasises the optical movement. The closely spaced rings take more drawing time than the simpler examples.'},
  'travelling-pinch': {title:'A surface contracts and opens',kind:'Local deformation',description:'The grid edges remain fixed. A soft dent moves across the middle and becomes a bulge, making the movement seem to happen inside the material.',controls:'Grid: 29 × 29 lines, Resolution 1 mm. Lens: Radius 44 mm, Use canvas center off. X = 45–95 mm; Strength = −0.9…0.9.',change:'Increase Radius for a broad breathing surface. A smaller radius makes the travelling dent more distinct.',plot:'The fixed outer grid provides a useful alignment reference between frames. The drawing needs no solid fills.'},
  'reassembly': {title:'A word breaks up and returns',kind:'Separation and reassembly',description:'The strokes of the letters break into short pieces and spread outwards. The same pieces return to their original positions, making the word readable again.',controls:'Text: TOGE|THER, Size 17 mm. Chop: Piece length 4 mm, one pen. Explosion: Strength 0–23 mm, Uniform, Seed 103.',change:'Use your own short word. Chop controls the size of each fragment; Explosion’s Spread controls the range of directions.',plot:'A short pen-down distance with many pen lifts. Keep Seed fixed in every frame.'},
  'letter-shift': {title:'Letters exchange places',kind:'Changing order',description:'The field stays full of letters. They change places row by row, carrying a rhythm through the text without moving the whole composition.',controls:'Fill region, text CHANGE, Motion Shift, Shift pattern Rows, Size 9 mm, Row lag 0.08. Phase input = 0–1.',change:'Try Shift pattern → Columns or Shuffle. Short words with distinct letter shapes make the changes easier to see.',plot:'Intentionally stepped movement rather than a smooth morph. A 24-frame loop suits the jumps between letters.'},
  'living-volume': {title:'A soft form reaches and retreats',kind:'Changing volume',description:'A continuous wire surface grows an extension, becomes asymmetric and returns. The viewing angles remain fixed throughout the loop.',controls:'Manual, 2 Balls. Ball 2 X = 15–70%, Ball 2 Z = −30…35%. Blend 55%, Noise 0, Size 108 mm; View angle 25°, elevation 20°.',change:'Change Ball 2 size or Blend. Keep Rings and Segments fixed throughout the animation so the mesh keeps its structure.',plot:'Back-facing lines are visible too. The node fits the form to its preview size, so the body’s proportions also change as the extension grows.'},
};
export const recipes = {
  lissajous:{title:'Lissajous · travelling phase',recipe:'Freq X 3, Freq Y 4, Turns 1, Damping 0; Phase = 2πu.'},
  aaltoilu:{title:'Grid → Wave · a travelling wave',recipe:'Grid: 12 horizontal lines. Wave: Amplitude 3 mm, Wavelength 36 mm; Phase = 2πu.'},
  grid_hairs:{title:'Grid Hairs · swaying cells',recipe:'Crosshatch, cells 20 × 20 mm, 5 lines per cell, Seed 28; Angle = 10 + 40w degrees.'},
  iris:{title:'Iris · a breathing pupil',recipe:'Human, Diameter 112 mm, 240 Fibres, Pupil finish Open, Seed 17; Pupil size = 0.18 + 0.24w.'},
  murmuration:{title:'Murmuration · a returning flock',recipe:'60 birds, Figure-8, Travel 0.3, Flock radius 25 mm, Scatter 3 mm, Size 1.4 mm, Seed 3; Time = u.'},
  plaid:{title:'Plaid · grids in depth',recipe:'3 Grids, Size 85, Cell min 14 / max 20, Bands 1, Bob 8°, Seed 7; Phase = u.'},
  ribbon:{title:'Ribbon · breathing pleats',recipe:'Organic / Pleated, 14 Lines, Bends 3, Flares 3, Seed 27; Width = 35 + 20w mm; Fold turns = 0.7 + 0.5w.'},
  concrete:{title:'Concrete Poetry · moving rows',recipe:'Columns, text LOOP, Size 9, Motion Wave, Clock Phase input, Distance 6, Amount 0.65; Phase = u.'},
};
export const animationPages=['animation/index.html','animation/combine-movements/index.html','animation/node-motion/index.html'];
