#!/usr/bin/env node
/** Run `node learn/generate-assets.mjs` to regenerate; use --check in validation. */
import assert from 'node:assert/strict';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { deflateSync } from 'node:zlib';
import { execFileSync } from 'node:child_process';
import { PENS_DEFAULT, pathLength } from '../src/defs/helpers.js';
import { DEFINITIONS, PILOT_KEYS, CANVAS, examples, blankPatch, evaluateExample, withParams, ports, defaults, makeTonalImage } from './lib/fixtures.mjs';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const CHECK = process.argv.includes('--check');
const appSource = await readFile(path.resolve(ROOT, '../src/App.jsx'), 'utf8');
const appVersion = appSource.match(/const APP_VERSION\s*=\s*"([^"]+)"/)?.[1];
assert.ok(appVersion, 'Muusia app version must be readable from its source');
const sourceCommit = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim();
const artifacts = new Map();
const json = value => JSON.stringify(value, null, 2) + '\n';
const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' }[c]));
const coord = value => Number(value.toFixed(4));

function stats(geometry) {
  return {
    paths: geometry.paths.length,
    points: geometry.paths.reduce((count, pa) => count + pa.pts.length, 0),
    drawingMm: Math.round(geometry.paths.reduce((total, pa) => total + pathLength(pa.pts, pa.closed), 0) * 10) / 10,
    travelMm: Math.round(travelDistance(geometry) * 10) / 10,
  };
}

function travelDistance(geometry) {
  let cursor = [0, 0], distance = 0;
  for (const pa of geometry.paths) {
    const start = pa.pts[0];
    distance += Math.hypot(start[0] - cursor[0], start[1] - cursor[1]);
    cursor = pa.closed ? start : pa.pts.at(-1);
  }
  return distance;
}

function svg(geometry, title, options = {}) {
  const { W, H } = CANVAS;
  const view = options.viewBox || [0, 0, W, H];
  const paths = geometry.paths.map(pa => {
    const color = PENS_DEFAULT[pa.layer]?.c || PENS_DEFAULT[0].c;
    const d = pa.pts.map((point, i) => `${i ? 'L' : 'M'}${coord(point[0])},${coord(point[1])}`).join(' ') + (pa.closed ? ' Z' : '');
    return `<path d="${d}" stroke="${color}"/>`;
  }).join('\n');
  let travel = '';
  if (options.showTravel) {
    let current = [0, 0];
    for (const pa of geometry.paths) {
      const first = pa.pts[0];
      travel += `<path d="M${current.map(coord).join(',')} L${first.map(coord).join(',')}"/>`;
      current = pa.closed ? first : pa.pts.at(-1);
    }
    travel = `<g fill="none" stroke="#df7b42" stroke-width="0.5" stroke-dasharray="2 2" opacity="0.6">${travel}</g>`;
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${view.join(' ')}" width="${view[2]}mm" height="${view[3]}mm" role="img" aria-labelledby="title desc">\n<title id="title">${escape(title)}</title>\n<desc id="desc">Generated by Muusia's actual node functions on a ${W} by ${H} mm canvas. All ${geometry.paths.length} paths are included.${options.showTravel ? ' Orange dashed lines show pen-up travel from the top-left origin, without a return move.' : ''}${options.annotations ? ' Measurement labels are explanatory and are not part of the downloadable plot.' : ''}</desc>\n<rect width="${W}" height="${H}" fill="#fff"/>\n${travel}\n<g fill="none" stroke-width="0.32" stroke-linecap="round" stroke-linejoin="round">${paths}</g>\n${options.annotations || ''}\n</svg>\n`;
}

function validateGraph(value) {
  const nodes = new Map(value.patch.root.nodes.map(n => [n.id, n]));
  assert.equal(nodes.size, value.patch.root.nodes.length, `${value.title}: duplicate node IDs`);
  const inputKeys = new Set();
  for (const e of value.patch.root.edges) {
    const source = nodes.get(e.from), target = nodes.get(e.to);
    assert.ok(source && target, `${value.title}: edge endpoint exists`);
    const output = ports(source, 'outs')[e.fromPort || 0];
    assert.ok(output, `${value.title}: source port exists`);
    const parameterPort = typeof e.toPort === 'string' && e.toPort.startsWith('p:');
    if (parameterPort) {
      const parameter = DEFINITIONS[target.type].params.find(p => p.key === e.toPort.slice(2));
      assert.ok(parameter && ['slider', 'number', 'seed'].includes(parameter.type), `${value.title}: numeric parameter port exists`);
      assert.equal(output.type, 'value', `${value.title}: parameter edge carries a number`);
    } else {
      const input = ports(target, 'ins')[e.toPort];
      assert.ok(input, `${value.title}: target input exists`);
      assert.equal(output.type, input.type, `${value.title}: edge types match`);
    }
    const inputKey = `${e.to}:${e.toPort}`;
    assert.ok(!inputKeys.has(inputKey), `${value.title}: one wire per input`);
    inputKeys.add(inputKey);
  }
}

function validateGeometry(geometry, title) {
  assert.ok(geometry?.paths?.length > 0, `${title}: non-empty output`);
  for (const pa of geometry.paths) {
    assert.ok(pa.pts.length > 1, `${title}: no degenerate path`);
    assert.ok(Number.isInteger(pa.layer) && pa.layer >= 0 && pa.layer < PENS_DEFAULT.length, `${title}: valid pen`);
    assert.ok(pa.pts.every(pt => pt.length === 2 && pt.every(Number.isFinite)), `${title}: finite 2D points`);
  }
}

function render(value, filename, title = value.title, options = {}) {
  validateGraph(value);
  const result = evaluateExample(value, options);
  validateGeometry(result.output, title);
  artifacts.set(filename, svg(result.output, title, options));
  return result;
}

function graph(value) {
  return {
    nodes: value.patch.root.nodes.map(n => ({ id: n.id, key: n.type, name: DEFINITIONS[n.type].name, params: n.params })),
    edges: value.patch.root.edges,
    outputId: value.outputId,
  };
}

function comparison(key, index, label, value, options = {}) {
  const src = `assets/comparisons/${key}-${index}.svg`;
  const result = render(value, src, `${DEFINITIONS[key].name}: ${label}`, options);
  return { label, src, stats: stats(result.output), ...(options.frameIdx !== undefined ? { frameIdx: options.frameIdx, frameCount: options.frameCount } : {}) };
}

function selectOutput(value, outputId) { return { ...value, outputId }; }

const comparisons = {
  grid: [8, 16, 24].map((hlines, i) => comparison('grid', i, `${hlines} horizontal lines`, withParams(examples.grid, 'grid', { hlines }))),
  aaltoilu: [0, 4, 8].map((amp, i) => comparison('aaltoilu', i, `Amplitude ${amp} mm`, withParams(examples.aaltoilu, 'aaltoilu', { amp }))),
  radat: [0, 4, 12].map((wob, i) => comparison('radat', i, `Shape noise ${wob}`, withParams(examples.radat, 'radat', { wob }))),
  viiva: ['Solid', 'Dashed', 'Dots'].map((mode, i) => comparison('viiva', i, mode, withParams(examples.viiva, 'viiva', { mode }))),
  stamp: [1.5, 2.5, 5].map((size, i) => comparison('stamp', i, `Size ${size} mm`, withParams(examples.stamp, 'stamp', { size }))),
  setpen: [
    comparison('setpen', 0, 'Input · Blue and Red pens', selectOutput(examples.setpen, 9006)),
    comparison('setpen', 1, 'Recolor All → pen 0 · Black', examples.setpen),
    comparison('setpen', 2, 'Recolor All → pen 3 · Green', withParams(examples.setpen, 'setpen', { layer: 3 })),
  ],
  merge: [
    comparison('merge', 0, 'Blue branch · Grid’s Pen setting', selectOutput(examples.merge, 9002)),
    comparison('merge', 1, 'Red branch · Tracks’ Pen setting', selectOutput(examples.merge, 9004)),
    comparison('merge', 2, 'Both branches merged', examples.merge),
  ],
  arvo: [0, 4, 10].map((v, i) => comparison('arvo', i, `Value ${v} → amplitude ${v} mm`, withParams(examples.arvo, 'arvo', { v }))),
  frame: [0, 1, 2].map((frameIdx, i) => comparison('frame', i, `Frame ${frameIdx + 1} of 12 · ${frameIdx * 30}°`, examples.frame, { frameIdx, frameCount: 12 })),
  image: ['Scanline wave', 'Halftone dots', 'Hatch levels'].map((mode, i) => comparison('image', i, mode, withParams(examples.image, 'image', { mode }))),
  polystudio: ['Concentric inset', 'Face hatch', 'Centroid fan'].map((fill, i) => comparison('polystudio', i, fill, withParams(examples.polystudio, 'polystudio', { fill }))),
  travelsort: [
    comparison('travelsort', 0, 'Before sorting', selectOutput(examples.travelsort, 9001), { showTravel: true }),
    comparison('travelsort', 1, 'After sorting', examples.travelsort, { showTravel: true }),
  ],
  move_scale: [
    comparison('move_scale', 0, 'Original closed loop', selectOutput(examples.move_scale, 9001)),
    comparison('move_scale', 1, 'Scale 70% · Scale Y 45%', examples.move_scale),
    comparison('move_scale', 2, 'Scale 70% · Scale Y 0 (same)', withParams(examples.move_scale, 'move_scale', { scaleY: 0 })),
  ],
  kierto: [0, 25, 65].map((deg, i) => comparison('kierto', i, `Angle ${deg}° · Per path on`, withParams(examples.kierto, 'kierto', { deg }))),
  hatch: [
    comparison('hatch', 0, 'Spacing 5 mm', withParams(examples.hatch, 'hatch', { spacing: 5 })),
    comparison('hatch', 1, 'Spacing 2.5 mm', examples.hatch),
    comparison('hatch', 2, 'Spacing 2.5 mm · Cross hatch on', withParams(examples.hatch, 'hatch', { cross: true })),
  ],
  container: [
    comparison('container', 0, 'Before cropping', selectOutput(examples.container, 9004)),
    comparison('container', 1, 'Keep Inside · Draw region on', examples.container),
    comparison('container', 2, 'Keep Outside · Draw region on', withParams(examples.container, 'container', { keep: 'Outside' })),
  ],
  satunnainen: [3, 11, 42].map((seed, i) => {
    const value = withParams(examples.satunnainen, 'satunnainen', { seed });
    const amplitude = evaluateExample(value).params[9005].amp;
    return comparison('satunnainen', i, `Seed ${seed} → amplitude ≈ ${amplitude.toFixed(2)} mm`, value);
  }),
  matem: [1, 2, 3].map((b, i) => comparison('matem', i, `4 × ${b} → amplitude ${4 * b} mm`, withParams(examples.matem, 'matem', { b }))),
};

const CATEGORY = { gen: 'Generators', mod: 'Modifiers', dec: 'Decorators', duo: 'Combiners', math: 'Math', route: 'Routing' };
const GROUP = { geometric: 'Geometric', deform: 'Deform', textimg: 'Text & Image', space: 'Space', penout: 'Pen & Output', transform: 'Transform', fillstyle: 'Fill & Style' };
const visibilityNotes = {
  "image.levels": "Shown only when Render is Contours (trace).",
  "image.low": "Shown only when Render is Contours (trace).",
  "image.high": "Shown only when Render is Contours (trace).",
  "image.minlen": "Shown only when Render is Contours (trace).",
  "image.drawingWidth": "Shown when Source is Auto or Drawing (wired); affects wired drawings only.",
  "image.drawingFill": "Shown when Source is Auto or Drawing (wired); affects wired drawings only.",
  "image.squarefill": "Shown only when Render is Square weave.",
  "image.squarelayout": "Shown only when Render is Square weave.",
  "image.dotfill": "Shown only when Render is Organic dots.",
  "image.direction": "Shown for Short strokes and Cross stitches.",
  "image.angle": "Shown for Short strokes and Cross stitches.",
  "image.flow": "Shown for Short strokes and Cross stitches unless Stroke direction is Fixed angle.",
  "image.passes": "Shown for Short strokes and Cross stitches.",
  "image.jitter": "Shown for Organic dots, Short strokes, Cross stitches and Square weave.",
  "image.pitch": "Shown for Organic dots, Short strokes, Cross stitches and Square weave.",
  "image.colours": "Shown for Organic dots, Short strokes, Cross stitches and Square weave.",
  "image.colourmap": "Shown for Organic dots, Short strokes, Cross stitches and Square weave when Colours is greater than 1.",
  "image.pen2": "Shown for Organic dots, Short strokes, Cross stitches and Square weave when Colours is at least 2.",
  "image.pen3": "Shown for Organic dots, Short strokes, Cross stitches and Square weave when Colours is at least 3.",
  "image.pen4": "Shown for Organic dots, Short strokes, Cross stitches and Square weave when Colours is at least 4.",
  "image.pen5": "Shown for Organic dots, Short strokes, Cross stitches and Square weave when Colours is at least 5.",
  "image.pen6": "Shown for Organic dots, Short strokes, Cross stitches and Square weave when Colours is at least 6.",
  sides: 'Shown for Prism, Antiprism, Pyramid, and Bipyramid.',
  freq: 'Shown for Geodesic sphere.',
  hatchAng: 'Shown when Face fill is Face hatch.',
  dotSize: 'Shown when Face fill is Dots.',
};
const manifest = {
  schemaVersion: 1,
  version: appVersion,
  sourceCommit,
  canvas: CANVAS,
  palette: PENS_DEFAULT,
  provenance: { generator: 'learn/generate-assets.mjs', fixtures: 'learn/lib/fixtures.mjs', command: 'node learn/generate-assets.mjs', validationCommand: 'node learn/generate-assets.mjs --check', geometry: 'Actual built-in node compute functions; no catalog point cap, no simulated screenshots.', sourceNote: 'Source commit records the checkout base; input hashes identify the exact working-tree sources used.', inputs: [] },
  nodes: [],
  tutorials: {},
  blankExample: 'examples/blank.muusia.json',
};

for (const [key, value] of Object.entries(examples)) {
  validateGraph(value);
  const result = evaluateExample(value);
  validateGeometry(result.output, value.title);
  assert.deepEqual(evaluateExample(value).out, result.out, `${key}: deterministic re-evaluation`);
  artifacts.set(`examples/${key}.muusia.json`, json(value.patch));
}
artifacts.set('examples/blank.muusia.json', json(blankPatch));

for (const key of PILOT_KEYS) {
  const def = DEFINITIONS[key], value = examples[key];
  const representative = value.patch.root.nodes.find(n => n.type === key);
  const output = `assets/results/${key}.svg`;
  const result = render(value, output);
  const params = def.params.map(p => {
    const { showIf, ...metadata } = p;
    if (!showIf) return { ...metadata, default: p.def, conditional: false, visibleByDefault: true };
    const visibilityNote = visibilityNotes[`${key}.${p.key}`] || visibilityNotes[p.key];
    assert.ok(visibilityNote, `${key}.${p.key}: conditional field needs an explicit explanation`);
    return { ...metadata, default: p.def, conditional: true, visibilityNote, visibleByDefault: showIf(defaults(key)) };
  });
  manifest.nodes.push({
    key, name: def.name, category: CATEGORY[def.cat], categoryKey: def.cat,
    group: GROUP[def.group] || CATEGORY[def.cat], groupKey: def.group || def.cat,
    params, inputs: ports(representative, 'ins'), outputs: ports(representative, 'outs'),
    dynamicInputs: typeof def.ins === 'function',
    ...(typeof def.ins === 'function' ? { inputsNote: 'Inputs evaluated with the example node parameters; changing Inputs changes the number of sockets.' } : {}),
    example: `examples/${key}.muusia.json`, output, screenshot: `assets/screenshots/${key}.png`, comparisons: comparisons[key],
    graph: graph(value), exampleParams: representative.params, outputId: value.outputId,
    stats: stats(result.output),
    ...(value.frameNote ? { frameNote: value.frameNote, frameCount: value.frameCount, frameIdx: value.frameIdx } : {}),
    ...(key === 'image' ? { sourceImage: 'assets/source/tonal-shapes.png', sourceNote: 'An original grayscale tonal study generated locally. The full raster data is embedded in this patch.' } : {}),
  });
}

const tutorialSteps = {
  first: [{ label: 'Grid: the source lines', nodeId: 9001 }, { label: 'Wave: the finished drawing', nodeId: 9002 }],
  stamps: [{ label: 'Tracks with the dashed Stroke applied', nodeId: 9002 }, { label: 'Stamp adds triangles and keeps the host paths', nodeId: 9003 }],
  'two-pens': [{ label: 'The blue Wave branch', nodeId: 9002 }, { label: 'The red Tracks branch', nodeId: 9004 }, { label: 'Both pen layers combined', nodeId: 9006 }],
  'svg-workflow': [{ label: 'File 01 · Pen 1 · Blue waves', nodeId: 9002 }, { label: 'File 02 · Pen 2 · Red loops', nodeId: 9004 }, { label: 'Aligned on the same sheet', nodeId: 9006 }],
  'transform-fill': [
    { label: 'Tracks · one closed blue loop', nodeId: 9001 },
    { label: 'Move / Scale · resize, then move', nodeId: 9002 },
    { label: 'Rotate · turn the closed loop 25°', nodeId: 9003 },
    { label: 'Hatch Fill · add vertical pen strokes', nodeId: 9004 },
    { label: 'Container · crop the strokes and add a black frame', nodeId: 9005 },
  ],
  numbers: [2, 4, 8].map(value => ({
    label: `Value ${value} × same seeded Random → amplitude ≈ ${(evaluateExample(examples['tutorial-numbers']).out[9003][0] * value).toFixed(2)} mm`,
    nodeId: 9005,
    changes: { type: 'arvo', params: { v: value } },
  })),
  'physical-plot': [
    { label: 'Scale · a 20 × 20 mm square', nodeId: 9001 },
    { label: 'Orientation · triangle points right', nodeId: 9002 },
    { label: 'Pen lifts · three separate strokes', nodeId: 9004 },
  ],
};
for (const key of Object.keys(tutorialSteps)) {
  const value = examples[`tutorial-${key}`];
  const output = `assets/results/tutorial-${key}.svg`;
  const result = render(value, output);
  const steps = tutorialSteps[key].map((step, i) => {
    const src = `assets/results/tutorial-${key}-step-${i + 1}.svg`;
    const stepValue = step.changes ? withParams(value, step.changes.type, step.changes.params) : value;
    render(selectOutput(stepValue, step.nodeId), src, step.label);
    return { ...step, src };
  });
  manifest.tutorials[key] = { key, title: value.title, example: `examples/tutorial-${key}.muusia.json`, output, steps, graph: graph(value), stats: stats(result.output) };
  if (key === 'svg-workflow') manifest.tutorials[key].exportBundle = { src: 'examples/svg-workflow-per-pen.zip', label: 'Download reference SVG set' };
  if (key === 'physical-plot') manifest.tutorials[key].exportBundle = { src: 'examples/physical-plot.svg', label: 'Download reference SVG', provenance: 'assets/screenshots/physical-plot-export.json' };
}

artifacts.set('assets/details/physical-plot.svg', svg(evaluateExample(examples['tutorial-physical-plot']).output,
  'First plot test — enlarged detail with a 20 mm measurement reference', {
    viewBox: [10, 8, 80, 64],
    annotations: '<g fill="none" stroke="#8d4c35" stroke-width="0.18"><path d="M20,16 H40 M20,14 V18 M40,14 V18"/></g><g fill="#8d4c35" font-family="monospace" font-size="2.4"><text x="30" y="12.5" text-anchor="middle">20 mm</text><text x="70" y="17" text-anchor="middle">Points right</text><text x="64.8" y="67" text-anchor="middle">Three separate strokes</text></g>',
  }));

// Verify important semantics, rather than merely checking that SVGs exist.
const valueResult = evaluateExample(examples.arvo);
assert.equal(valueResult.params[9003].amp, 4, 'Value drives the numeric amplitude socket');
assert.deepEqual(evaluateExample(examples.frame, { frameIdx: 1, frameCount: 12 }).out[9001], [1 / 11, 1, 0.5 - 0.5 * Math.cos(Math.PI / 6), 1 / 6, 30], 'Frame exposes all five true outputs');
const sortResult = evaluateExample(examples.travelsort);
const before = sortResult.out[9001][0], after = sortResult.output;
function segmentSet(geometry) {
  const segments = [];
  for (const pa of geometry.paths) {
    for (let i = 0; i < pa.pts.length - 1 + (pa.closed ? 1 : 0); i++) {
      const ends = [pa.pts[i], pa.pts[(i + 1) % pa.pts.length]].map(pt => pt.map(coord).join(',')).sort();
      segments.push(`${pa.layer}:${ends.join('|')}`);
    }
  }
  return segments.sort();
}
assert.deepEqual(segmentSet(before), segmentSet(after), 'Travel Sort preserves every drawn segment and pen');
assert.ok(travelDistance(after) < travelDistance(before), 'Travel Sort reduces pen-up distance in this fixture');
const colored = evaluateExample(examples.setpen);
assert.deepEqual([...new Set(colored.out[9006][0].paths.map(p => p.layer))].sort(), [1, 2], 'Set Pen receives a multi-pen composition');
assert.deepEqual(colored.output.paths.map(p => p.pts), colored.out[9006][0].paths.map(p => p.pts), 'Set Pen leaves the complete composition geometry unchanged');
assert.ok(colored.output.paths.every(p => p.layer === 0), 'Set Pen consolidates both input pens onto Black');
const merged = evaluateExample(examples.merge);
assert.equal(merged.output.paths.length, merged.out[9002][0].paths.length + merged.out[9004][0].paths.length, 'Merge keeps both complete branches');
assert.deepEqual([...new Set(merged.out[9002][0].paths.map(p => p.layer))], [1], 'Wave preserves the Blue pen chosen in Grid');
assert.deepEqual([...new Set(merged.out[9004][0].paths.map(p => p.layer))], [2], 'Tracks supplies its own Red pen');
const poly = evaluateExample(examples.polystudio).out[9001];
assert.ok(poly[1].paths.length > 0 && poly[2], 'Polyhedron Studio retains silhouette and mesh outputs');
manifest.validation = { examples: Object.keys(examples).length, nodes: PILOT_KEYS.length, deterministic: true, typedEdges: true, finiteCoordinates: true, travelSortPreservesSegments: true, travelSortBeforeMm: stats(before).travelMm, travelSortAfterMm: stats(after).travelMm, note: 'Travel distances start at (0,0), include pen-up moves between paths, and exclude a return-to-origin move. Turn off Optimize route in the app to inspect this node alone.' };

// Tiny dependency-free PNG encoder for the exact embedded grayscale source.
function crc32(buffer) {
  let c = 0xffffffff;
  for (const byte of buffer) {
    c ^= byte;
    for (let bit = 0; bit < 8; bit++) c = (c >>> 1) ^ ((c & 1) ? 0xedb88320 : 0);
  }
  return (c ^ 0xffffffff) >>> 0;
}
function chunk(type, bytes) {
  const tag = Buffer.from(type), size = Buffer.alloc(4), checksum = Buffer.alloc(4);
  size.writeUInt32BE(bytes.length);
  checksum.writeUInt32BE(crc32(Buffer.concat([tag, bytes])));
  return Buffer.concat([size, tag, bytes, checksum]);
}
const tonal = makeTonalImage(), header = Buffer.alloc(13);
header.writeUInt32BE(tonal.w, 0); header.writeUInt32BE(tonal.h, 4); header[8] = 8; header[9] = 0;
const pixels = Buffer.alloc((tonal.w + 1) * tonal.h);
for (let y = 0; y < tonal.h; y++) for (let x = 0; x < tonal.w; x++) pixels[y * (tonal.w + 1) + x + 1] = tonal.rgb[(y * tonal.w + x) * 3];
artifacts.set('assets/source/tonal-shapes.png', Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk('IHDR', header), chunk('IDAT', deflateSync(pixels, { level: 9 })), chunk('IEND', Buffer.alloc(0))]));
artifacts.set('assets/source/README.md', '# Original image fixture\n\n`tonal-shapes.png` is an original grayscale study created by `makeTonalImage()` in `learn/lib/fixtures.mjs`. It contains a shaded circle, a tonal rectangle, and a gradient bar. The PNG pixels exactly match the raster embedded in `examples/image.muusia.json`. No external images are used.\n');

for (const relative of ['learn/generate-assets.mjs', 'learn/lib/fixtures.mjs', 'src/defs/helpers.js', ...PILOT_KEYS.map(key => `src/defs/nodes/${key}.js`)]) {
  const bytes = await readFile(path.resolve(ROOT, '..', relative));
  manifest.provenance.inputs.push({ path: relative, sha256: createHash('sha256').update(bytes).digest('hex') });
}
manifest.provenance.artifacts = [...artifacts.entries()].map(([file, content]) => ({ path: file, sha256: createHash('sha256').update(content).digest('hex') }));
artifacts.set('generated/manifest.json', json(manifest));
for (const [relative, content] of artifacts) {
  const full = path.join(ROOT, relative);
  if (CHECK) assert.deepEqual(await readFile(full), Buffer.from(content), `Stale generated asset: ${relative}`);
  else { await mkdir(path.dirname(full), { recursive: true }); await writeFile(full, content); }
}
console.log(`${CHECK ? 'Verified' : 'Generated'} ${artifacts.size} reproducible assets; ${PILOT_KEYS.length} nodes and ${Object.keys(tutorialSteps).length} tutorials. Travel Sort: ${stats(before).travelMm} → ${stats(after).travelMm} mm.`);
