/* make-catalog.mjs — generates src/defs/catalog.js from docs/MUUSIA-NODES.md
 *
 * Sources:
 *   - src/defs/nodes/*.js          -> key/name/cat/hidden per node (imported live)
 *   - docs/MUUSIA-NODES.md         -> one search paragraph per node (the doc-batch text)
 *   - docs/MUUSIA-TAGS.json        -> optional curated tags { key: ["tag", ...] } (Phase 2)
 *
 * Output: src/defs/catalog.js  ->  export const CATALOG = { key: { t: "text", tags: [...] } }
 *
 * Run from repo root:  node tools/make-catalog.mjs
 * Regenerate in every doc batch (NODES.md paragraph changed => catalog changed).
 * validate-catalog.mjs fails the build gate if the committed file is stale.
 */

import fs from "fs";
import path from "path";
import { pathToFileURL } from "url";

const ROOT = process.cwd();
const NODES_DIR = path.join(ROOT, "src/defs/nodes");
const NODES_MD = path.join(ROOT, "docs/MUUSIA-NODES.md");
const TAGS_JSON = path.join(ROOT, "docs/MUUSIA-TAGS.json");
const OUT = path.join(ROOT, "src/defs/catalog.js");

/* Engine-bound defs living in App.jsx, mapped by their NODES.md paragraph names */
const ENGINE_DEFS = { Group: "group", Route: "reititys" };

export async function buildCatalog() {
  const report = { matched: 0, missingParagraph: [], orphanParagraphs: [], unknownTagKeys: [] };

  /* 1 — load every node def */
  const files = fs.readdirSync(NODES_DIR).filter((f) => f.endsWith(".js")).sort();
  const defs = [];
  for (const f of files) {
    const mod = await import(pathToFileURL(path.join(NODES_DIR, f)).href);
    const d = mod.default;
    defs.push({ key: d.key, name: d.name, hidden: !!d.hidden });
  }
  const byName = new Map(defs.map((d) => [d.name.toLowerCase(), d]));

  /* 2 — parse NODES.md paragraphs: a node entry starts a paragraph with **Name** */
  const md = fs.readFileSync(NODES_MD, "utf8");
  const entries = [];
  let cur = null, prevBlank = true, inSection = false;
  for (const line of md.split("\n")) {
    if (/^## /.test(line)) { if (cur) entries.push(cur); cur = null; inSection = true; prevBlank = false; continue; }
    const m = inSection && prevBlank ? line.match(/^\*\*([^*]+)\*\*(.*)$/) : null;
    if (m) {
      if (cur) entries.push(cur);
      cur = { name: m[1].trim(), text: m[2] };
    } else if (cur) {
      if (/^---/.test(line)) { entries.push(cur); cur = null; }
      else cur.text += " " + line;
    }
    prevBlank = line.trim() === "";
  }
  if (cur) entries.push(cur);

  const clean = (s) =>
    s.replace(/\*+/g, "")            /* markdown emphasis */
     .replace(/^[\s—–-]+/, "")       /* leading em-dash */
     .replace(/\s+/g, " ")
     .trim();

  /* 3 — optional curated tags */
  let tags = {};
  if (fs.existsSync(TAGS_JSON)) {
    tags = JSON.parse(fs.readFileSync(TAGS_JSON, "utf8"));
    const known = new Set([...defs.map((d) => d.key), ...Object.values(ENGINE_DEFS)]);
    report.unknownTagKeys = Object.keys(tags).filter((k) => !known.has(k));
  }

  /* 4 — match paragraphs to defs */
  const catalog = {};
  for (const e of entries) {
    const key = ENGINE_DEFS[e.name] || (byName.get(e.name.toLowerCase()) || {}).key;
    if (!key) { report.orphanParagraphs.push(e.name); continue; }
    catalog[key] = { t: clean(e.text), tags: (tags[key] || []).map((t) => String(t).toLowerCase()) };
    report.matched++;
  }
  for (const d of defs) {
    if (!catalog[d.key]) {
      report.missingParagraph.push(d.key + " (" + d.name + ")");
      catalog[d.key] = { t: "", tags: (tags[d.key] || []).map((t) => String(t).toLowerCase()) };
    }
  }

  /* 5 — emit, deterministic key order */
  const keys = Object.keys(catalog).sort();
  const body = keys
    .map((k) => "  " + JSON.stringify(k) + ": { t: " + JSON.stringify(catalog[k].t) +
                ", tags: " + JSON.stringify(catalog[k].tags) + " },")
    .join("\n");
  const code =
    "/* AUTO-GENERATED by tools/make-catalog.mjs — do not edit by hand.\n" +
    " * Source of truth: docs/MUUSIA-NODES.md (+ docs/MUUSIA-TAGS.json).\n" +
    " * Regenerate in every doc batch: node tools/make-catalog.mjs */\n" +
    "export const CATALOG = {\n" + body + "\n};\n";

  return { code, report };
}

const isMain = process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url;
if (isMain) {
  const { code, report } = await buildCatalog();
  fs.writeFileSync(OUT, code);
  console.log("OK   wrote src/defs/catalog.js (" + report.matched + " paragraphs matched, " +
              (code.length / 1024).toFixed(1) + " kB)");
  if (report.missingParagraph.length)
    console.log("WARN " + report.missingParagraph.length + " nodes have NO paragraph in NODES.md (doc debt):\n     " +
                report.missingParagraph.join("\n     "));
  if (report.orphanParagraphs.length)
    console.log("WARN paragraphs matching no node (name drift?): " + report.orphanParagraphs.join(", "));
  if (report.unknownTagKeys.length)
    console.log("WARN MUUSIA-TAGS.json keys matching no node: " + report.unknownTagKeys.join(", "));
}
