/** Reproducible review gallery from the real node, not browser-export evidence.
 * node tools/render-iris.mjs /tmp/muusia-iris-pilot
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import iris from '../src/defs/nodes/iris.js';
import { PENS_DEFAULT, pathLength } from '../src/defs/helpers.js';
const out = resolve(process.argv[2] || '/tmp/muusia-iris-pilot');
await mkdir(out, { recursive: true });
const defaults = Object.fromEntries(iris.params.map(p => [p.key, p.def]));
const studies = [
  ['six-colours', '07 / Six colours', 'A3 · black, orange, blue, teal, purple and ochre', { colours:'Six pens', layer:0, innerPen:4, accentPen:1, midtonePen:6, outerPen:5, highlightPen:10 }, { W:420, H:297 }],
  ['human', '01 / Human', 'A3 · 277 mm · one black pen', {}, { W:420, H:297 }],
  ['cat', '02 / Cat', 'A3 · vertical slit · teal, orange and black', { species:'Cat', colours:'Three pens', layer:6, innerPen:4, accentPen:0 }, { W:420, H:297 }],
  ['goat', '03 / Goat', 'A3 · horizontal pupil · ochre and black', { species:'Goat', colours:'Two pens', layer:10, innerPen:0, flow:0.3 }, { W:420, H:297 }],
  ['gecko', '04 / Gecko', 'A3 · stylised notched slit · green, ochre and black', { species:'Gecko', colours:'Three pens', layer:3, innerPen:10, accentPen:0 }, { W:420, H:297 }],
  ['rays', '05 / Centre rays', 'A3 · all fibres start at one point · two pens', { centre:'Centre rays', colours:'Two pens', layer:1, innerPen:0, texture:0.3, flow:0.8, fray:0.6 }, { W:420, H:297 }],
  ['large', '06 / Large study', '440 × 440 mm sheet · 420 mm iris · open pupil', { diameter:420, fibres:1400, pupilFill:'Open' }, { W:440, H:440 }],
];
const cards = [], records = [];
for (const [id,title,subtitle,overrides,ctx] of studies) {
  const params = { ...defaults, ...overrides }, output = iris.compute([undefined],params,ctx);
  const layers = [...new Set(output.paths.map(p=>p.layer))].sort((a,b)=>a-b);
  const groups = layers.map(layer => `<g id="pen-${layer}" stroke="${PENS_DEFAULT[layer].c}">${output.paths.filter(p=>p.layer===layer).map(p=>`<path d="${p.pts.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(4)},${y.toFixed(4)}`).join(' ')}${p.closed?' Z':''}"/>`).join('\n')}</g>`).join('\n');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${ctx.W}mm" height="${ctx.H}mm" viewBox="0 0 ${ctx.W} ${ctx.H}"><title>${title}</title><g fill="none" stroke-width="0.22" stroke-linecap="round" stroke-linejoin="round">${groups}</g></svg>`;
  const patch = { app:'muusia',v:1,name:`Iris — ${id}`,canvas:ctx,root:{nodes:[{id:9001,type:'iris',x:30,y:20,params}],edges:[]} };
  await writeFile(`${out}/${id}.svg`,svg);
  await writeFile(`${out}/${id}.muusia.json`,JSON.stringify(patch,null,2)+'\n');
  const drawingM = output.paths.reduce((n,p)=>n+pathLength(p.pts,p.closed),0)/1000;
  records.push({id,canvas:ctx,parameters:params,paths:output.paths.length,points:output.paths.reduce((n,p)=>n+p.pts.length,0),drawingM,layers});
  cards.push(`<article><a href="${id}.svg"><img src="${id}.svg" alt="${title}, generated by the actual Iris node"/></a><div><h2>${title}</h2><p>${subtitle}</p><p class="meta">${output.paths.length.toLocaleString('en')} paths · ${drawingM.toFixed(1)} m of drawing</p><a href="${id}.muusia.json" download>Editable Muusia patch ↓</a> · <a href="${id}.svg" download>Vector drawing ↓</a></div></article>`);
}
await writeFile(`${out}/manifest.json`,JSON.stringify(records,null,2)+'\n');
await writeFile(`${out}/index.html`, `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Iris — Muusia node pilot</title><style>*{box-sizing:border-box}body{margin:0;background:#f5f3ed;color:#272720;font:16px/1.6 system-ui,sans-serif}header,main,footer{max-width:1400px;margin:auto;padding:32px 5vw}header{border-bottom:1px solid #bdbbb1}header p{max-width:760px}h1{font:clamp(54px,8vw,110px)/1 Georgia,serif;margin:20px 0}header small{letter-spacing:.16em}main{display:grid;grid-template-columns:1fr 1fr;gap:48px 28px}article{min-width:0}article img{display:block;width:100%;height:auto;background:#fff}h2{font:30px/1.3 Georgia,serif;margin:18px 0 4px}p{margin:5px 0 12px}a{color:inherit;text-underline-offset:4px}.meta,footer{color:#65645e;font-size:14px}footer{border-top:1px solid #bdbbb1}@media(max-width:700px){main{grid-template-columns:1fr}}</style><header><small>MUUSIA / NODE STUDY 01</small><h1>Iris</h1><p>Organic fibres, animal-inspired pupils and real pen layers. These ${studies.length} studies are generated by the actual node. Open a vector drawing to inspect its full detail; load a patch into the local pilot build to edit it.</p><p><a href="http://127.0.0.1:5186/">Open the local Muusia pilot →</a> &nbsp; Help → Iris · Six colours</p></header><main>${cards.join('')}</main><footer><p>Local pilot; not yet a published Muusia release. Animal forms are stylised. A full 420 mm circle needs a sheet larger than A3. Stroke appearance here uses a 0.22 mm line; physical results depend on your pen and paper. Generated node SVGs are review artwork, not evidence of a browser export or physical plot.</p><p>Shape inspiration: <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC4643806/">Banks et al., Why do animal eyes have pupils of different shapes? (2015)</a>. The gecko preset uses a continuous decorative slit instead of separate apertures.</p></footer></html>`);
console.log(`Wrote ${studies.length} node-generated SVGs, patches and review gallery to ${out}`);
